# Generated by Django 2.1.3 on 2018-11-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseInfo',
            fields=[
                ('courseid', models.CharField(db_column='CourseID', max_length=10, primary_key=True, serialize=False)),
                ('coursename', models.CharField(blank=True, db_column='CourseName', max_length=50, null=True)),
                ('studyhour', models.IntegerField(blank=True, db_column='StudyHour', null=True)),
                ('credit', models.DecimalField(blank=True, db_column='Credit', decimal_places=1, max_digits=18, null=True)),
                ('teststy', models.CharField(blank=True, db_column='TestSty', max_length=4, null=True)),
                ('comment', models.CharField(blank=True, db_column='Comment', max_length=50, null=True)),
            ],
            options={
                'db_table': 'course_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coursetype',
            fields=[
                ('coursetype', models.CharField(db_column='CourseType', max_length=5, primary_key=True, serialize=False)),
                ('coursetypename', models.CharField(blank=True, db_column='CourseTypeName', max_length=50, null=True)),
            ],
            options={
                'db_table': 'coursetype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CultivateScheme',
            fields=[
                ('schemeid', models.DecimalField(db_column='SchemeID', decimal_places=0, max_digits=9, primary_key=True, serialize=False)),
                ('grade', models.CharField(db_column='Grade', max_length=4)),
                ('year', models.CharField(db_column='Year', max_length=9)),
                ('term', models.CharField(db_column='Term', max_length=5)),
                ('teststy', models.CharField(blank=True, db_column='TestSty', max_length=4, null=True)),
            ],
            options={
                'db_table': 'cultivate_scheme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DeptInfo',
            fields=[
                ('deptid', models.CharField(db_column='DeptID', max_length=10, primary_key=True, serialize=False)),
                ('deptname', models.CharField(blank=True, db_column='DeptName', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=2000, null=True)),
                ('isused', models.TextField(blank=True, db_column='IsUsed', null=True)),
            ],
            options={
                'db_table': 'dept_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('name', models.CharField(db_column='Name', max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=45, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nation',
            fields=[
                ('nationid', models.CharField(db_column='NationID', max_length=2, primary_key=True, serialize=False)),
                ('nationname', models.CharField(blank=True, db_column='NationName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'nation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Policate',
            fields=[
                ('policateid', models.CharField(db_column='Policateid', max_length=2, primary_key=True, serialize=False)),
                ('policatename', models.CharField(blank=True, db_column='Policatename', max_length=24, null=True)),
            ],
            options={
                'db_table': 'policate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_field', models.CharField(blank=True, db_column='Class', max_length=4, null=True)),
                ('tutorid', models.CharField(blank=True, db_column='TutorID', max_length=10, null=True)),
                ('score', models.FloatField(blank=True, db_column='Score', null=True)),
                ('selectcurrtime', models.DateTimeField(blank=True, db_column='SelectCurrTime', null=True)),
            ],
            options={
                'db_table': 'select_course',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('sex', models.CharField(db_column='Sex', max_length=1, primary_key=True, serialize=False)),
                ('sexname', models.CharField(blank=True, db_column='SexName', max_length=10, null=True)),
            ],
            options={
                'db_table': 'sex',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SpecialityInfo',
            fields=[
                ('specialityid', models.IntegerField(db_column='SpecialityID', primary_key=True, serialize=False)),
                ('specialityno', models.CharField(blank=True, db_column='SpecialityNo', max_length=8, null=True)),
                ('specialityname', models.CharField(blank=True, db_column='SpecialityName', max_length=50, null=True)),
                ('specialitydescription', models.CharField(blank=True, db_column='SpecialityDescription', max_length=2000, null=True)),
                ('deptid', models.CharField(blank=True, db_column='DeptID', max_length=10, null=True)),
                ('tutordescript', models.CharField(blank=True, db_column='TutorDescript', max_length=5000, null=True)),
                ('isused', models.TextField(blank=True, db_column='IsUsed', null=True)),
            ],
            options={
                'db_table': 'speciality_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('graduateid', models.CharField(db_column='GraduateID', max_length=10, primary_key=True, serialize=False)),
                ('graduatename', models.CharField(blank=True, db_column='GraduateName', max_length=20, null=True)),
                ('birthday', models.DateTimeField(blank=True, db_column='Birthday', null=True)),
                ('idcardno', models.CharField(blank=True, db_column='IDcardNo', max_length=18, null=True)),
                ('grade', models.CharField(blank=True, db_column='Grade', max_length=4, null=True)),
                ('specialityid', models.IntegerField(blank=True, db_column='SpecialityID', null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=14, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=50, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=50, null=True)),
            ],
            options={
                'db_table': 'student_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorInfo',
            fields=[
                ('tutorid', models.CharField(db_column='TutorID', max_length=10, primary_key=True, serialize=False)),
                ('tutorname', models.CharField(blank=True, db_column='TutorName', max_length=20, null=True)),
                ('tutorbirthday', models.DateTimeField(blank=True, db_column='TutorBirthday', null=True)),
                ('tutordescript', models.CharField(blank=True, db_column='TutorDescript', max_length=5000, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=40, null=True)),
                ('homepage', models.CharField(blank=True, db_column='HomePage', max_length=100, null=True)),
                ('tel', models.CharField(blank=True, db_column='Tel', max_length=15, null=True)),
            ],
            options={
                'db_table': 'tutor_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tutorlevel',
            fields=[
                ('tutorlevel', models.CharField(db_column='TutorLevel', max_length=3, primary_key=True, serialize=False)),
                ('levelname', models.CharField(blank=True, db_column='LevelName', max_length=20, null=True)),
            ],
            options={
                'db_table': 'tutorlevel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TutorspecRelationship',
            fields=[
                ('tutorid', models.CharField(db_column='TutorID', max_length=10, primary_key=True, serialize=False)),
                ('specialityid', models.IntegerField(db_column='SpecialityID')),
                ('tutordate', models.DateTimeField(blank=True, db_column='TutorDate', null=True)),
            ],
            options={
                'db_table': 'tutorspec_relationship',
                'managed': False,
            },
        ),
    ]
